name: bcr_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - backports.zstd=1.5.0
  - biopython=1.87
  - blast=2.16.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.5.20
  - curl=8.19.0
  - cutadapt=5.2
  - deprecated=1.3.1
  - dnaio=1.2.2
  - entrez-direct=22.4
  - flash2=2.2.00
  - icu=78.3
  - igblast=1.22.0
  - isa-l=2.31.1
  - krb5=1.22.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.19.0
  - libcxx=22.1.2
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.8.1
  - libffi=3.4.8
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.25.1
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.68.1
  - libopenblas=0.3.33
  - libsqlite=3.52.0
  - libssh2=1.11.1
  - libunistring=0.9.10
  - libzlib=1.3.1
  - llvm-openmp=22.1.7
  - nanofilt=2.8.0
  - nanoget=1.19.4
  - nanomath=1.4.0
  - nanostat=1.6.0
  - ncbi-vdb=3.4.1
  - ncurses=6.5
  - numpy=2.2.6
  - openssl=3.6.2
  - packaging=26.0
  - pandas=2.3.3
  - pbzip2=1.1.13
  - pcre2=10.47
  - perl=5.32.1
  - perl-archive-tar=3.12
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.214
  - perl-compress-raw-zlib=2.214
  - perl-encode=3.24
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.216
  - perl-io-zlib=1.15
  - perl-json=4.11
  - perl-json-xs=4.04
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.70
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pigz=2.8
  - pip=26.1.1
  - pysam=0.23.3
  - python=3.10.20
  - python-dateutil=2.9.0.post0
  - python-isal=1.8.0
  - python-tzdata=2026.2
  - python-zlib-ng=1.0.0
  - python_abi=3.10
  - pytz=2026.2
  - readline=8.3
  - rpsbproc=0.5.1
  - setuptools=82.0.1
  - six=1.17.0
  - sqlite=3.51.2
  - tk=8.6.15
  - tzdata=2026b
  - wget=1.25.0
  - wheel=0.46.3
  - wrapt=2.2.1
  - xopen=2.1.0
  - xz=5.8.2
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.63.0
      - kiwisolver==1.5.0
      - lxml==6.1.1
      - matplotlib==3.10.9
      - openpyxl==3.1.5
      - pillow==12.2.0
      - pyparsing==3.3.2
      - python-docx==1.2.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - typing-extensions==4.15.0
